name: Deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mdbook
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook
          version: "0.4.40"
      - name: Install mdbook-katex
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-katex
          version: "0.9.0"
      - name: Print mdbook and plugins version
        run: |
          mdbook --version
          mdbook-katex --version
      - name: Build book
        run: mdbook build
      - name: Setup Pages
        uses: actions/configure-pages@v5
        id: pages
      - name: Upload mdbook
        uses: actions/upload-artifact@v4
        with:
          path: ./book

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
